from __future__ import annotations
import numpy as np
from typing import Dict, Tuple
from .utils import response_log_likelihood

def run_on_sequence(
    model: BaseModel,
    observations: np.ndarray,
    sigma_r: float,
    responses: np.ndarray | None = None,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """
    Simulate a model on a deterministic stimulus sequence.
    Returns (beliefs, responses, prediction_errors).
    If `responses` is None, responses are generated by adding Gaussian noise.
    """
    T = len(observations)
    beliefs = np.empty(T, dtype=float)
    pred_err = np.empty(T, dtype=float)
    out_resp = np.empty(T, dtype=float)

    model.reset(float(observations[0]))

    # trial 0 (no update yet)
    beliefs[0] = model.predict()
    pred_err[0] = observations[0] - beliefs[0]
    out_resp[0] = (
        beliefs[0] + np.random.randn() * sigma_r
        if responses is None
        else float(responses[0])
    )

    for t in range(1, T):
        # prediction based on the previous posterior
        beliefs[t] = model.predict()
        pred_err[t] = observations[t] - beliefs[t]

        # generate / copy response before we ingest the new observation
        out_resp[t] = (
            beliefs[t] + np.random.randn() * sigma_r
            if responses is None
            else float(responses[t])
        )

        # now absorb the observation
        model.update(float(observations[t]))

    return beliefs, out_resp, pred_err